export const GET_TICKERS_DATA = 'GET_TICKERS_DATA';
export const STOP_UPDATE_TICKER = 'STOP_UPDATE_TICKER';
export const START_UPDATE_TICKER = 'START_UPDATE_TICKER';
export const DELETE_TICKER = 'DELETE_TICKER';


